name: Creating a Workflow that uses the secret
on: push
jobs:
    secret_testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out the code
              uses: actions/checkout@v3
            - name: Printing secret value
              run: echo "Using API key:${{secrets.API_KEY}}"
